### PR TITLE
fixed README

### PR DESCRIPTION
**Pull request by kambehmw**
Fixed parameter arguments of evaluation.

### CODE REVIEW

**Comment by parasj** [comment]
Hi @kambehmw -- I will release this updated model, apologies for the omission of the type prediction fine-tuned model checkpoint. I think your PR is good; I will update the Google Drive directory structure to match, and then will merge it.

**Comment by parasj** [comment]
@ajayjain Can you update the folder names in the Google Drive to match @kambehmw's PR? Thanks!

**Comment by parasj** [comment]
@kambehmw After discussing with Ajay, we decided to add your updates as instructions to the readme. https://github.com/parasj/contracode/commit/80df7ab6958a65c7f990a35a1fc63da41bf0a267

**Comment by kambehmw** [comment]
@parasj 
Thank you for adding the updates to the README.

>  I will release this updated model, apologies for the omission of the type prediction fine-tuned model checkpoint. 

As a confirmation, I think what is missing in the Google drive is the fine-tuned model of the method naming task.
I'd appreciate it if you could make this one available in the future as well.

**Pull request closed without merging**
